
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_order_system_development
  username: postgres
  password: 719171

test:
  <<: *default
  database: restaurant_order_system_test
  username: postgres
  password: 719171

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: restaurant_order_system_production
  username: restaurant_order_system
  password: <%= ENV["RESTAURANT_ORDER_SYSTEM_DATABASE_PASSWORD"] %>
